 {
     "env": {
       "browser": true,
       "es2021": true,
       "node": true
     },
     "extends": [
       "eslint:recommended",
       "plugin:jest/recommended"
     ],
     "parserOptions": {
       "ecmaVersion": 12,
       "sourceType": "module"
     },
     "rules": {
       "quotes": ["error", "double"],
       "linebreak-style": ["error", "unix"],
       "indent": ["error", 2],
       "no-unused-vars": ["error"]
     }
   }